# If you are using mssql, derby, hsqldb, h2 or oracle with one of the
# ActiveRecord JDBC adapters, configure your database setting as the
# example below. (Note that for oracle you will need to include the
# driver jar on the classpath.):
#
#development:
#  adapter: mssql
#  username: <username>
#  password: <password>
#  host: localhost
#  database: dummy

# If you are using db2, sybase, informix or prefer to directly specify
# the JDBC connection information, configure your database setting as
# the example below (requires you to download and manually install the
# database vendor's JDBC driver .jar file). See your driver
# documentation for the apropriate driver class and connection string:
#
#development:
#  adapter: jdbc
#  username: <username>
#  password: <password>
#  driver: com.ibm.db2.jcc.DB2Driver
#  url: jdbc:db2://localhost:5021/dummy

# PostgreSQL. Versions 8.2 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On Mac OS X with macports:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
development:
    adapter: jdbcpostgresql
    username: bcs
    password: bawama8i
    encoding: unicode
    database: bcs
    host: logan.pp.bcinfra.net:8973

  # Connect on a TCP socket. Omitted by default since the client uses a
  # domain socket that doesn't need configuration. Windows does not have
  # domain sockets, so uncomment these lines.
  #host: localhost
  #port: 5432

  # Schema search path. The server defaults to $user,public
  #schema_search_path: myapp,sharedapp,public

  # Minimum log levels, in increasing order:
  #   debug5, debug4, debug3, debug2, debug1,
  #   log, notice, warning, error, fatal, and panic
  # The server defaults to notice.
  #min_messages: warning

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
    adapter: jdbcpostgresql
    username: bcs
    password: bawama8i
    encoding: unicode
    database: bcs
    host: logan.pp.bcinfra.net:8973
    
production:
    adapter: jdbcpostgresql
    username: bcs
    password: bawama8i
    encoding: unicode
    database: bcs
    host: logan.pp.bcinfra.net:8973
